name: smart_pay_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.1
  flutter_svg_provider: ^1.0.6
  connectivity: ^3.0.6
  flutter_localization: ^0.2.0
  dio: ^5.4.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  country_picker: ^2.0.21
  marquee: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500

